[package]
name = "vold"
version = "0.1.0"
edition = "2021"
authors = ["Andrew <khimchuk.io@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.30.0"
home = "0.5.9"
rpassword = "7.3.1"
