#!/usr/bin/env sh

MYPATH=$(pwd)

if [ $# -eq 0 ]; then
    echo "Problem parsing argument: No argument found"
    echo "Try:"
    echo ""
    echo "  --> quick help"
    echo ""
    exit 1
fi

key="$1"

case $key in
    help)
        echo "Using:"
        echo ""
        echo "  quick install           install qpass"
        echo "  quick uninstall         uninstall qpass"
        echo ""
        exit 0
        ;;
    install)
        cargo build --release --verbose
        cargo install --path $MYPATH
        ;;
    uninstall)
        rm -rf $HOME/.qpass_storage
        cargo clean
        cargo uninstall
        ;;
    *)
        echo "Problem parsing argument: Unknow argument $1"
        echo "Try:"
        echo ""
        echo "  --> quick help"
        echo ""
        exit 1
        ;;
esac
