#!/usr/bin/env sh

MYPATH=$(pwd)

if [ $# -eq 0 ]; then
    echo "Parsing error: *** No options were passed."
    echo "Using: quick [ARGUMENT]"
    echo ""
    echo "Options:"
    echo "  install         install QPass"
    echo "  uninstall       uninstall QPass"
    exit 1
fi

key="$1"

case $key in
    help)
        echo "Using: quick [ARGUMENT]"
        echo ""
        echo "Options:"
        echo "  install         install QPass"
        echo "  uninstall       uninstall QPass"
       exit 0
        ;;
    install)
        cargo build --release --verbose
        cargo install --path $MYPATH
        ;;
    uninstall)
        rm -rf $HOME/.qpass_storage
        cargo clean
        cargo uninstall
        ;;
    *)
        echo "Parsing error: *** Unknow option '$1'."
        echo "Try: quick help"
        exit 1
        ;;
esac
